[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@selfxyz/contracts/contracts/=lib/self/contracts/contracts/",
]

[rpc_endpoints]
celo = "https://forno.celo.org"
celo-sepolia = "https://forno.celo-sepolia.celo-testnet.org"
localhost = "http://localhost:8545"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
